---
title: "math for IBM"
author: "Lisa Rosenthal"
date: "4/3/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here's the math for a generic continuous time disease model with one species. C, S, and I are the number of individuals in states challenged, susceptible, and infected, respectively. Challenged individuals can become infected either through inoculum-plant transmission ($\alpha(t)C$) or plant-plant transmission ($\beta(t)CI$). We identify these two tranmission modes as "primary" and "secondary", respectively. The two transmission coefficients vary with time. ($\alpha(t)$) decays expontentially with time, causing any uninfected challenged individuals to effectively become susceptibles after a period of time; ($\beta(t)$) increases as root zones increase and decrease as plants become more resistant with age. Since we assume that inoculum can only infect individuals a short distance away (i.e. the "challenged" individuals), susceptible individuals can only be infected through secondary transmission ($\beta(t)SI$). 


$$
\begin{aligned}
\frac{dC}{dt} &= -\alpha(t)C -\beta(t)CI \\
\frac{dS}{dt} &= -\beta(t)SI \\
\frac{dI}{dt} &= \alpha(t)C +\beta(t)CI +  \beta(t)SI\\
\end{aligned}
$$

When I extend the above model to a multihost community, I need to account for the species-specific primary $\alpha_i(t)$ and secondary $\beta_{ij}(t)$ transmission coeffiecents. Since secondary transmission involves two plants, a donor and reciepent, every pairwise combination must be estimated. Here, each species *i* can be infected by all species *j*, where $j=1, 2,... s$ number of species. 

$$
\begin{aligned}
\frac{dC_i}{dt} &= -\alpha_i(t)C_i -C_i\sum_j\beta_{ij}(t)I_j \\
\frac{dS_i}{dt} &= -S_i\sum_j\beta_{ij}(t)I_j \\
\frac{dI_i}{dt} &= \alpha_i(t)C_i +(C_i + S_i)\sum_j\beta_{ij}(t)I_j \\
\end{aligned}
$$

In order to account for the spatial dynamics of disease spread, I must model space explicitly. The above models are spatially implicit and assume that all individuals are interacting equally and therefore have an equal probability of being infected. However, this assumption is oversimplifying, especially in small populations. To model space, I'm running an individual based model where each cell in a hexagonal lattice has an associated probability of transmission. An individual's infection probability is sensitive to the species identities of itself and its neighbors.  

I have two models: one that assumes infections can only occur between nearest neighbors and one that assumes that contact rates decay with distance. For both, transmission varies with time. Currently, the $\alpha(t)$ and $\beta(t)$ curves originate from Otten et al. (2003), which were estimated from *Rhizoctonia solani* infections on radish. I am assuming that species with different competencies only changes the amplitude of those distributions.    

To incorporate the spatial element of transmission between species, let 
$$\beta_{x_iI_j}(t, r) = c_{x_iI_j}(r)p_{ij}(t)$$ 
which describes the transmission rate between an infected individual $I_j$ and a susceptible or challenged individual $x_i$ that are $r$ distance units apart. Transmission is a product of $c_{x_iI_j}(r)$, the contact rate, and $p_{ij}(t)$, the probability of transmission given contact between species $j$ and species $i$. For the nearest neighbor model, we assume $r=1$ for neighbors directly adjacent and $r=0$ for all others. For the model with distance decay, $r$ is the pairwise distance between individuals.

I must discretize the continuous time equations above and have it recalculated at each time step. I am defining each time step to be 1 day.  

An individual $x_i$ either staying or transitioning between states is determined by a binomial process, with the probabilities defined below:

$$
\begin{aligned}
P(C \rightarrow I)_{x_i} &= 1 - exp(-(\alpha_i(t) + \sum_j\beta_{x_iI_j}(t, r)I_j))\\
P(C \rightarrow C)_{x_i} &= exp(-(\alpha_i(t) + \sum_j\beta_{x_iI_j}(t, r)I_j))\\
P(S \rightarrow I)_{x_i} &= 1 - exp(- \sum_j\beta_{x_iI_j}(t, r)I_j)\\
P(S \rightarrow S)_{x_i} &= exp(- \sum_j\beta_{x_iI_j}(t, r)I_j)\\
P(I \rightarrow I)_{x_i} &= 1\\
\end{aligned}
$$

In the IBM simulation, I run a loop that says at every time step, for every individual, determine if there will be stasis or a transition. A random draw from a binomial distribution is pulled, determined by the probabilities defined above, deciding the "fate" of each individual's next state. I record the states of all individuals for the duration of the simulation. 








